avrdude.exe -c 2232HIO -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c 4232h -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c 89isp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c abcmini -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c alf -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c arduino -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c arduino-ft232r -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c atisp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c avr109 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c avr910 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c avr911 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c avrftdi -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c avrisp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c avrisp2 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c avrispmkII -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c avrispv2 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c bascom -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c blaster -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c bsd -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c buspirate -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c buspirate_bb -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c butterfly -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c butterfly_mk -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c bwmega -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c c2n232i -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c dapa -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c dasa -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c dasa3 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c diecimila -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c dragon_dw -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c dragon_hvsp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c dragon_isp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c dragon_jtag -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c dragon_pdi -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c dragon_pp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c dt006 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c ere-isp-avr -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c frank-stk200 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c ft232r -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c ft245r -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c futurlec -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag1 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag1slow -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag2 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag2avr32 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag2dw -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag2fast -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag2isp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag2pdi -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag2slow -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag3 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag3dw -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag3isp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtag3pdi -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtagkey -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtagmkI -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtagmkII -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c jtagmkII_avr32 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c lm3s811 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c mib510 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c mkbutterfly -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c nibobee -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c o-link -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c openmoko -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c pavr -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c pickit2 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c picoweb -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c pony-stk200 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c ponyser -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c siprog -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c sp12 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c stk200 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c stk500 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c stk500hvsp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c stk500pp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c stk500v1 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c stk500v2 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c stk600 -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c stk600hvsp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c stk600pp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c usbasp -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c usbasp-clone -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c usbtiny -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c wiring -p atmega168 -U flash:w:SensorHostUSB.hex:i
avrdude.exe -c xil -p atmega168 -U flash:w:SensorHostUSB.hex:i
